version: '3'
services:
    download-covert-uploader:
        build:
            context: .
        restart:
            always
        network_mode: "host"  
        ports:
          - "8006:8006"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app